### PR TITLE
Remove some deprecation & other warnings

### PR DESCRIPTION
**Pull request by xuanruiqi**
While experimenting with the interpreter I found some deprecation warnings were generated, so I went ahead and changed the offending code.

### CODE REVIEW

**Comment by garrigue** [comment]
Thank you, this was very old code, and I couldn't understand all the warnings...

**Comment by xuanruiqi** [comment]
However, I cannot figure out how to get rid of `Unused introduction patterns`...

**Comment by garrigue** [comment]
That one is really strange. It seems to be triggered by the implicit `auto` in `apply*`, so there is probably something wrong in my Ltac code somewhere, but I'm not sure what.

**Comment by garrigue** [comment]
Ok, it's in `fresh_solve`. But it's a rather complex tactic.

**Comment by garrigue** [comment]
Ok, it's caused by the `destructs` tactic in `Lib_tactic`, when it's called on something with not enough components. Not sure how to avoid that.

**Comment by xuanruiqi** [comment]
The fix for `destructs` is surprisingly easy! Basically, instead of making a recursive call, using `repeat` avoids the problems.

**Pull request merged**
